run:
  timeout: 5m

linters:
  enable:
    - errcheck    
    - gosimple    
    - govet       
    - ineffassign 
    - staticcheck 
    - typecheck
    - unused      
    - gocyclo     

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false