### Create Log
### 1. Create a Log (Trigger Async Flow)
#  201 Created. (ID = 0)
POST http://localhost:8080/logs
Content-Type: application/json

{
    "service_name": "cache-demo",
    "level": "INFO",
    "message": "I am a log"
}

### 2. Get Log by ID 
# if is db first data GET ID = 1
# "[Cache] Miss, querying DB..."
GET http://localhost:8080/logs/5

### 3. Get Log by ID 
# request again
# "[Cache] Hit" 
GET http://localhost:8080/logs/5

### 4. Check Health 
GET http://localhost:8080/ping


### Search for "timeout"
GET http://localhost:8080/logs/search?q=timeout

### Search for "login"
GET http://localhost:8080/logs/search?q=login